### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by qq0310** [biofuture/Ublastx_stageone#12]
您好，我在试运行时，一直遇到如下错误，能否请老师帮忙看一下，非常感谢！
另外，我想问下，input文件夹中，是否可以直接放gz压缩文件。
---Fatal error---
Unknown file format /media/sf_ZQQ/zqqraw/inputqq/one_1.fa

/home/qqq/ARGsOAP/Ublastx_stageone/bin/usearch -ublast /media/sf_ZQQ/zqqraw/inputqq/one_2.fa -db /home/qqq/ARGsOAP/Ublastx_stageone/DB/gg85.udb -evalue 1e-10 -accel 0.5 -blast6out output//one_2.16s -threads 1 -strand both -maxaccepts 1

---Fatal error---
Unknown file format /media/sf_ZQQ/zqqraw/inputqq/one_2.fa
Error: zlib: Z_DATA_ERROR: invalid distance too far back
Error: zlib: Z_DATA_ERROR: invalid distance too far back
cat: output//one.uscmg_1.dmd: No such file or directory
cat: output//one.uscmg_2.dmd: No such file or directory

**Comment by biofuture** [comment]
​如果是gz需要设置添加  -z 运行第一步的时候 ​

Regards,

Xiao-Tao Jiang, Ph.D.
Department of Civil Engineering
The University of HongKong

2018-04-03 17:34 GMT+08:00 qq0310 <notifications@github.com>:

**Comment by qq0310** [comment]
关于压缩文件的问题已经解决了 非常感谢姜老师的帮助！
现在我在尝试用ARGs-OAP处理自己的宏基因组数据，遇到了另外一个问题，就是32位的usearch不能处理超过4G的数据。想咨询下老师，这个问题有没有解决办法。
我尝试过用vsearch代替usearch，把脚本中提到的usearch改为vsearch，但是运行失败。报错内容主要如下：Ublastx_stageone/bin/vsearch: unrecognized option '-ublast'。所以接下来不知道该怎么解决这个问题了。
期待您的回复，非常感谢！
