### ISSUE TITLE
Stagetwo file upload fail

### ISSUE THREAD

**Issue by kkanger** [biofuture/Ublastx_stageone#13]
Hi,
I'm trying to upload the extracted.fa (84.5 Mb) and meta_data_online.txt to Galaxy ARGs-OAP v2.0, but keep getting status errors "Failed: Bad Gateway (502)" or "Failed: Bad Request (400)". 
Could you help?
Thanks!
Kärt

**Comment by biofuture** [comment]
Dear Kart

Please refresh the page and upload again, it will work, the server became
unstable after updating.

Regards,

Xiao-Tao Jiang, Ph.D.
Department of Civil Engineering
The University of HongKong

2018-04-05 18:39 GMT+08:00 kkanger <notifications@github.com>:

**Comment by kkanger** [comment]
Thanks for your suggestions!
However, refreshing the page doesn't work. I tried it several times yesterday and today, but I keep getting the same error messages. 
Any other ideas?
Thanks!
