### ISSUE TITLE
stageone result different

### ISSUE THREAD

**Issue by chloelulu** [biofuture/Ublastx_stageone#14]
Hi, 
I am using this software to analyze the shotgun data. However, the output only contains the following files after stage one. No 16s_hvr_community.txt,16s_hvr_normal.copy.txt,16s_hyperout.txt.....Is there anything wrong? Since I still have the extracted.fa and meta_data_online.txt, I can still run the stagetwo.
Thanks in advance.
`22TB_D2_L008_group_1.16s  22TB_D2_L008_group.extract_1.fa  22TB_D2_L008_group.uscmg.blastx.txt         meta_data_online.txt
22TB_D2_L008_group_1.us   22TB_D2_L008_group.extract_2.fa  22TB_D2_L008_group.uscmg.ko_averagecov.txt  ublastx_bash_Mon-Apr-9-17:25:14-2018.sh
22TB_D2_L008_group_2.16s  22TB_D2_L008_group.uscmg_1.dmd   extracted.fa
22TB_D2_L008_group_2.us   22TB_D2_L008_group.uscmg_2.dmd   Log.txt
`

**Comment by biofuture** [comment]
No worried. The updated version do not use hyper variable region to get cell numbers.  So there is no such files 

发自我的 iPhone

**Comment by chloelulu** [comment]
Hi, @biofuture ,
Thanks so much. I see. 
Since my shotgun data is paired-end and each sample is so big that I split my raw reads into 6 sub fastq files. Then I imported the meta_data.txt with contains 6 lines. And I put all the subfiles into the inputfqs folder. Then I got each sample with a meta-data-online.txt and one extracted.fa from stage one. Then I import thees two files into the galaxy to run. As a result, I got the final three table with each sample with 6 columns, which shows each sub fastq ARG count. 
I have enclosed the stageone produced file and stagetwo produced file. May I know how to deal with the final result? For this sample, I just sum up each row? Then the final number will be the this sample's normalized abundance or abundance?
Thanks so much.
[meta_data_online_18TB_C1_L002.txt](https://github.com/biofuture/Ublastx_stageone/files/1892768/meta_data_online_18TB_C1_L002.txt)
[Galaxy64-[Subtype,_type,_and_merged_subtype_and_environmental_samples_ARGs_abundance_matrix,_ARG_abundance_normalized_agaist_16S_reads_number].txt](https://github.com/biofuture/Ublastx_stageone/files/1892769/Galaxy64-.Subtype._type._and_merged_subtype_and_environmental_samples_ARGs_abundance_matrix._ARG_abundance_normalized_agaist_16S_reads_number.txt)
[Galaxy65-[Subtype,_type,_and_merge_subtype_and_environmental_samples_ARGs_abundance_matrix,_ARG_abundance_normalized_aganist__cell_number].txt](https://github.com/biofuture/Ublastx_stageone/files/1892770/Galaxy65-.Subtype._type._and_merge_subtype_and_environmental_samples_ARGs_abundance_matrix._ARG_abundance_normalized_aganist__cell_number.txt)
[Galaxy66-[Merge_type_and_subtype_ARG_abundance_table__the_value_represent_number_of_reads_per_million_reads_in_each_sample].txt](https://github.com/biofuture/Ublastx_stageone/files/1892771/Galaxy66-.Merge_type_and_subtype_ARG_abundance_table__the_value_represent_number_of_reads_per_million_reads_in_each_sample.txt)
