### ISSUE TITLE
About option -s

### ISSUE THREAD

**Issue by qq0310** [biofuture/Ublastx_stageone#15]
姜老师您好，我用测试数据运行的时候，加了option-s，代码如下：
../argoap_pipeline_stageone_version2  -i inputfqs/ -m meta-data.txt  -o output1/ -s
结果发现，meta_data_online.txt文件中，of16Sreads值变为原来的两倍，如下：SampleID	Name	Category	LibrarySize	#ofReads	#of16Sreads	CellNumber
1	STAS	ST	300	200000	16.7025139664804	3.05466168640877
2	SWHAS104	SWH	300		200000	15.0167597765363	3.35835780796717
我想问下，这是否是因为测试文件过小。
期待您的回复！

**Comment by biofuture** [comment]
-s option has some problem.  There probably some difference between the 32 bit and 64-bit version of usearch.  We will report bugs to usearch developer.
