### ISSUE TITLE
About stagetwo

### ISSUE THREAD

**Issue by qq0310** [biofuture/Ublastx_stageone#16]
您好，我在本地运行stagetwo脚本时，脚本没有输出任何结果就结束了，代码如下：
./argoap_pipeline_stagetwo_version2 -i <extracted.fa> -m <meta_data_online.txt> o <output_prefix>
另外，我尝试上传文件至http://smile.hku.hk/SARGs 处理，但是每次进程运行时都会出错，上传测试数据处理时也是这样。
期待您的回复！

**Comment by biofuture** [comment]
你好，我理解你是直接运行上面的命令， 你这个<extracted.fa> 需要是 extracted.fa 同理其它<>都不可以有的哦， 还有-o 不是 o，  web应该是可以用的， 需要刷一下， 我们回头会解决系统不稳定的问题。 祝你顺利

**Comment by qq0310** [comment]
您好，我不是直接运行上面的命令的，是因为代码关闭了所以复制了这段，我自己运行的时候<>都是没有的。但是每次程序都是直接结束，没有任何输出的。

**Comment by biofuture** [comment]
你可以把你运行的命令给我看看嘛？ 如果方便的话把extracted.fa和meta_data_online.txt文件，发我邮箱，我可以帮你看看

**Comment by biofuture** [comment]
你的meta_data_online.txt 有问题， 少一列数。 还有你那些R包有安装吗？ 确保你的系统的R能够调用 vegan

**Comment by qq0310** [comment]
我检查了自己的文件，发现stageone的时候，我的meta-data.txt文件没有填 library size 这一列，请问这是否影响步骤一的结果呢，是否需要重新做stageone。这个library size指的是什么呢。
我还没有blastx比对的中间结果，R包已经安装好了。
