### ISSUE TITLE
About ARGpore

### ISSUE THREAD

**Issue by qq0310** [biofuture/Ublastx_stageone#20]
您好，我想问下，如果想在线使用ARGpore，应该提交什么格式的文件呢。
期待您的回复~

**Comment by biofuture** [comment]
fasta 格式提交就可以，建议用sustc的server: smile.sustc.edu.cn:8080

Regards,

Xiao-Tao Jiang, Ph.D.
Postdoc Research Fellow
Microbiome Research Centre
St George and Sutherland Clinical School
UNSW Sydney

Level 2, Clinical Sciences Building (WR Pitney)
Short Street, St George Hospital
KOGARAH NSW 2217
T: +61 402 943 681
Email: biofuture.jiang@gmail.com/xiaotao.jiang@unsw.edu.au

2018-05-15 10:31 GMT+08:00 qq0310 <notifications@github.com>:

**Comment by qq0310** [comment]
谢谢您的回复～
请问是原始测序数据的fasta格式吗～

发自我的 iPhone

**Comment by qq0310** [comment]
您好，ARGpore ARGs-host tracking pipeline是不是只能用于nanopore测序呀，可以用于Illumina测序数据吗~
期待您的回复~

**Comment by smallwhitelama** [comment]
您好，請問要如何使用ARGpore服務，我上傳了幾組nanopore的fasta檔案，但都失敗了。請問能請您協助嗎
謝謝您


訊息為：
error
此数据集发生错误:
home/lg209ws3/argoap/galaxy/tools/hostract/BlastTab.addlen.rb:11: warning: constant ::FALSE is deprecated
/home/lg209ws3/argoap/galaxy/tools/hostract/BlastTab.addlen.rb:11: warning: constant ::FALSE is deprecated
/home/lg209ws3/argoap/galaxy/tools/hostr
