### ISSUE TITLE
SARGfam

### ISSUE THREAD

**Issue by Katterinne** [biofuture/Ublastx_stageone#22]
Hello ! Thank you for your pipeline and for your work building this amazing database! It really solve the problem of have to do the manual classification of the AR genes that one could find through comparisons against ARDB and CARD.

My question: SARGfam database is publicly available for download? So I can run HMMSCAN on my own, no through Galaxy. I read at "Availability and implementation" in the abstract section of your ARGs-OAP v2.0 paper, that the database could be downloaded from the Galaxy page, but I have not been successful finding how to do that.

Would appreciate your help!

Regards,

Katterinne

**Comment by biofuture** [comment]
Dear  Katterinne N. Mendez

The database is already on the DB directory.  Check
https://github.com/biofuture/Ublastx_stageone

The DATABASE FILE of SARG2.0
<https://github.com/biofuture/Ublastx_stageone/blob/master/DB/SARG_20170328_12307.fasta>
and
the structure
<https://github.com/biofuture/Ublastx_stageone/blob/master/DB/structure_20170328_12037.LIST>
of
the database are under the DB directory.
​
Regards,

Xiao-Tao Jiang, Ph.D.
Postdoc Research Fellow
Microbiome Research Centre
St George and Sutherland Clinical School
UNSW Sydney

Level 2, Clinical Sciences Building (WR Pitney)
Short Street, St George Hospital
KOGARAH NSW 2217
T: +61 402 943 681
Email: biofuture.jiang@gmail.com/xiaotao.jiang@unsw.edu.au


Katterinne N. Mendez <notifications@github.com> 于2018年7月10日周二 下午11:39写道：

**Comment by Katterinne** [comment]
Dear Xiao-Tao Jiang,

Thank you for your answer.

Thank you for your answer. I had already noticed the presence of SARG database under "DB" directory. But, I was looking for HMM profiles (SARGfam database), are they available or should I build the HMM profiles?

Regards,

Katterinne

**Comment by slvrshot** [comment]
> Dear Xiao-Tao Jiang,
> 
> Thank you for your answer.
> 
> I had already noticed the presence of SARG database under "DB" directory. But, I was looking for HMM profiles (SARGfam database), are they available or should I build the HMM profiles?
> 
> Regards,
> 
> Katterinne

DId you ever figure this out? The galaxy instance is really slow so doing it locally would be ideal.

**Comment by Katterinne** [comment]
No, I didn't. I also tried to use Galaxy, but it was impossible. I needed to do it locally -as you say, it would be ideal-, but neither I find the HMM profiles nor I received an answer to my question, so I just give up on this and used [ARGs_OAP pipeline](https://github.com/biofuture/Ublastx_stageone) (stage one and two for local running ) using blast as search engine (*although having the HMM profiles would be great*). I also use the [Resfams](http://www.dantaslab.org/resfams) database that have the HMM profiles available for download.

**Comment by slvrshot** [comment]
The galaxy version is super slow but I reached out to Xiaole and she she updated her repository and added the profiles as a .zip file: https://github.com/xiaole99/ARGs-OAP-v2.0.

These are the profiles: https://github.com/xiaole99/Sargfam/blob/master/Sargfam.zip

This is the exact script that galaxy uses:
`hmmscan --cut_ga --tblout output_file_name --cpu 1 DB/Sargfam.hmm intput_ORF
`
(hmmscan is version 3.1b1)

I used this to put out sequence ids for the ORFs containing ARGs: 
awk '{print $3}' yourfile.txt > ARG_ORFs_file.txt

Then seqkit to put them out of the original assembled fastas. 

`cat file.fasta | seqkit grep -r -f ARG_ORFs_file.txt > ARG_ORFs.fa `

You can wrap this into parallel gnu to make it run super fast in parallel.

**Comment by Katterinne** [comment]
This is great, I'll try it on my data ! Thank you very much for doing this and for sharing !

**Comment by slvrshot** [comment]
> This is great, I'll try it on my data ! Thank you very much for doing this and for sharing !

If you're feeling like using parallel on multiple assemblies this is how I do it:

This is get the sequence ids from every samples hmmscan output:
`awk '{if(FILENAME!=prev){close(prev)};print $3 > (FILENAME".ids.txt");prev=FILENAME}'  *.txt`

then in the directory with the original assembled sequence files, run this and it will extract all the ARG containing ORFs from every sample in parallel. You may need to tweak this based on how you named your samples:

`parallel 'cat {} | seqkit grep -f {.}.ids.txt > {.}.output.fa' ::: *fa
`
You're very welcome! Good luck!

**Comment by biofuture** [comment]
Hi, for the HMM

you can get access to it with our web server  https://smile.hku.hk/SARGs

Regards,

Xiao-Tao Jiang, Ph.D.
Postdoc Research Fellow
Microbiome Research Centre
St George and Sutherland Clinical School
UNSW Sydney

Level 2, Clinical Sciences Building (WR Pitney)
Short Street, St George Hospital
KOGARAH NSW 2217
T: +61 402 943 681
Email: biofuture.jiang@gmail.com/xiaotao.jiang@unsw.edu.au
MRC web: https://microbiome.org.au/


slvrshot <notifications@github.com> 于2019年7月31日周三 上午5:59写道：

**Comment by diego00012138** [comment]
Hi,
    Out of concern of timeliness, as today is 2025, I can not use the data from 2018. However, the website "https://smile.hku.hk/SARGs" seems to have crashed. Can you update the SARGfam anywhere it is accessible.
    Hope to hear from you soon.
Sincerely
