### ISSUE TITLE
Passing -s flag during stage one: Split files not rejoined

### ISSUE THREAD

**Issue by amgrube** [biofuture/Ublastx_stageone#26]
Hello, 
I am concerned that passing the -s flag during stage one of the pipeline results in the fastq files being split but not rejoined. To test whether the -s flag was working properly, I executed the same script on the same set of paired-end files and got a significant difference in the number of mapped reads whether the -s flag was included or not: 14115 mapped reads when the -s flag was not passed versus 4058 when the -s flag was passed. I performed this test on a set of paired-end files that were small enough to be processed in stage one without needing to be split (about 250MB combined). Previously I ran stage one on files that were too large and included the -s flag, but had no way of knowing that the files had not rejoined since I could not compare to the case where the -s flag was not used. It was not until I included the -s flag on a smaller set of files that I realized the split files were not rejoining. 

Has anyone else run into this problem, and do you have any recommendations? Since I'm using the 32-bit version and do need to split large files for stage one, my only thought is to manually split the files after quality filtering, run them separately through stage one, and concatenate the results before proceeding to stage two.

Thanks in advance for your help!

**Comment by amgrube** [comment]
For reference, these are the scripts I ran: 

No splitting (-s flag omitted)
/nas/longleaf/apps/ublastx/2018-04/argoap_pipeline_stageone_version2 -i /proj/stewartlab/projects/Rapid/qual_test/ALAGlev0/seqs -o /proj/stewartlab/projects/Rapid/qual_test/ALAGlev0/out/ -m /proj/stewartlab/projects/Rapid/qual_test/ALAGlev0/meta.txt -n 10

Splitting (-s flag passed)
/nas/longleaf/apps/ublastx/2018-04/argoap_pipeline_stageone_version2 -i /proj/stewartlab/projects/Rapid/qual_test/ALAGlev0/seqs -o /proj/stewartlab/projects/Rapid/qual_test/ALAGlev0/ -m /proj/stewartlab/projects/Rapid/qual_test/ALAGlev0/meta.txt -n 10 -s

**Comment by biofuture** [comment]
Thanks for raising this problem.   There should not be so much difference!  Could you have a check about  whether the splitting is correct or not?   Under the bin directory, there is a script responsible for splitting!~

**Comment by amgrube** [comment]
Thank you for your response! This is what the script for splitting in the bin directory looks like. How can I check if the script it working properly? Thank you!

[agrube@longleaf-login2 bin]$ cat merge_split.pl 
#!/usr/bin/perl -w
use strict;

die "perl $0 <indir> <db> <nuc/pro> <evalue> <out1> <out2> <threads> <bindir>\n" unless (@ARGV == 8);

opendir my $dirtmp, "$ARGV[0]" or die "Cannot open directory: $!";
my @files = readdir $dirtmp;
closedir $dirtmp;
my $ublastxdir = $ARGV[7];

for my $ftmp1 (@files){
#	die "$ftmp1\n";
	if($ftmp1 =~ m/\_1.fa$/){
		my $ftmp2 = $ftmp1;
		$ftmp2 =~ s/\_1.fa/\_2.fa/;
		die "not exist the pair\n" unless(-e "$ARGV[0]/$ftmp2");                           
		my $otmp1 = "$ARGV[0]/$ftmp1\_tmp1";
		my $otmp2 = "$ARGV[0]/$ftmp2\_tmp2";
		##process the pair of splitted fa 
		if($ARGV[2] eq "pro"){
			##search SARG database using usearch 
		`$ublastxdir/bin/usearch -ublast $ARGV[0]/$ftmp1 -db $ARGV[1] -evalue $ARGV[3] -accel 0.5 -blast6out $otmp1 -threads $ARGV[6] -maxaccepts 1`;
		`$ublastxdir/bin/usearch -ublast $ARGV[0]/$ftmp2 -db $ARGV[1] -evalue $ARGV[3] -accel 0.5 -blast6out $otmp2 -threads $ARGV[6] -maxaccepts 1`;
		}elsif($ARGV[2] eq "nuc"){
			##do usearch against greengene nr90 database to calculate 16S copies number
		`$ublastxdir/bin/usearch -ublast $ARGV[0]/$ftmp1 -db $ARGV[1] -evalue $ARGV[3] -accel 0.5 -blast6out $otmp1 -threads $ARGV[6] -strand both  -maxaccepts 1`;
		`$ublastxdir/bin/usearch -ublast $ARGV[0]/$ftmp2 -db $ARGV[1] -evalue $ARGV[3] -accel 0.5 -blast6out $otmp2 -threads $ARGV[6] -strand both  -maxaccepts 1`;
		}

	}
}
##merge all 

opendir my $dirupdate, "$ARGV[0]";
my @updatefiles = readdir $dirupdate;
close $dirupdate;

for my $fo1 (@updatefiles){
	if($fo1 =~ m/\_tmp1$/){
		my $fo2 = $fo1;
		$fo2 =~ s/\_1\.fa\_tmp1/\_2\.fa\_tmp2/;
		if(-e "$ARGV[0]/$fo2"){
			##merge all the split results 
			`cat $ARGV[0]/$fo1 >> $ARGV[4]`;
			`cat $ARGV[0]/$fo2 >> $ARGV[5]`;
			
		}else{
			die "Wrong $ARGV[0]/$fo1\n";
		}
	}
}

**Comment by amgrube** [comment]
[merge_split.txt](https://github.com/biofuture/Ublastx_stageone/files/2867645/merge_split.txt)
