### ISSUE TITLE
no reads in extracted.fa and no 16S reads

### ISSUE THREAD

**Issue by anotherXinzhu** [biofuture/Ublastx_stageone#28]
I have got no reads in the extracted.fa file after running the argoap_pipeline.stageone_version2 codes, and the number of 16S reads is 0. However, I do have 1500 to 2800 as the CellNumber, which I am not sure is normal or not. 

Could you advise on what might have gone wrong and what could I try next?

Thank you.

**Comment by biofuture** [comment]
There must be some wrong with searching the 16S and SARG database, please check the log information to see the error message!

**Comment by anotherXinzhu** [comment]
>           There must be some wrong with searching the 16S and SARG database, please check the log information to see the error message!

Thanks for the reply.

No error message in the log files but I figured it out: my fastq files are too big. 
I compare my few files on why some of the files work and why some don't.  The fastq files bigger than 7,300,000KB has this issue.  Then I split the fastq files into half.  The programming is still running but I can see there are reads in the .16s files and .us files.
