### ISSUE TITLE
Would it be possible to use custom database?

### ISSUE THREAD

**Issue by slvrshot** [biofuture/Ublastx_stageone#29]
I'm curious if this program could be utilized with a custom database. I have some samples that I mapped using diamond blastx to another protein database and created my own extracted.fa. The 16S reads in theory should be the same since I originally ran the program on the same dataset. I'd like to generate the mother tables using the abundance of my custom ARGs to copies of 16S but I'm unsure of how I could make this work. Would you be able to assist me?

**Comment by biofuture** [comment]
If you use a custom database, you should have the type/subtype information
of these ARGs (or other genes) to generate a structure file and replace the
structure file in stage two script,  it is not straightforward to use the
stage two script in this case.
You had better to generate the abundance of each gene firstly and then
directly divide the abundance by the  16S number.

Regards,

Xiao-Tao Jiang, Ph.D.
Postdoc Research Fellow
Microbiome Research Centre
St George and Sutherland Clinical School
UNSW Sydney

Level 2, Clinical Sciences Building (WR Pitney)
Short Street, St George Hospital
KOGARAH NSW 2217
T: +61 402 943 681
Email: biofuture.jiang@gmail.com/xiaotao.jiang@unsw.edu.au
MRC web: https://microbiome.org.au/


slvrshot <notifications@github.com> 于2019年1月8日周二 下午12:09写道：

**Comment by slvrshot** [comment]
@biofuture 

Would you be able to point to some package or software that would help me create an abundance table for my custom gene database? Thanks so much!
