### ISSUE TITLE
Contigs as input

### ISSUE THREAD

**Issue by koopkaup** [biofuture/Ublastx_stageone#3]
I have a feature request to use single fasta file (contigs) as an input not paired-end reads. Is it possible to add?

And have you updated the SARG database that is used in the second phase? CARD database have been updated several times recently with new subunits and mutations.

Thank you!

**Comment by biofuture** [comment]
Dear Koopkaup

As this pipeline is designed for short reads, it is not well supported for contigs, we will added the annotation and quantification of contigs in the future update.
