### ISSUE TITLE
meta_data_online.txt is empty

### ISSUE THREAD

**Issue by Bio-finder** [biofuture/Ublastx_stageone#32]
Good morning,
I've been using your nice tool on my data and in the end of the first step, I end up with an file of extracted.fa which contains sequences but the meta_data_online.txt is empty and just contains the header without any sample. 
My first metadata file looks like this
` SampleID        Name    Category`
`1       A10     A`
`2       A11     A`

 so it contains all the information needed and result files are generated for my samples but the final_results files contains the name of something else so I suppose that it generated this from your example dataset if metadata_online.txt is empty.  Do you know what  could cause such a thing?
Thanks in advance for your help.

**Comment by biofuture** [comment]
1. Please check your  meta data file format using NodePad++ under windows if you work under windows, make sure the end of each line is LF rather than LFCR
2. Make sure that all the software under the bin/ directory is executable

**Comment by Bio-finder** [comment]
Hi, I checked this but sadly it didn't changed anything. 
This time I've take a closer look at the errors generated during the run and Here's what I got:


Line 154 /home/ampere/bbergkpi/softwares/ARGs_OAP/Ublastx_stageone/bin/merge_extracted_fa_update_metadate.pl Not KO Maping, wrong datasets
Use of uninitialized value in concatenation (.) or string at /home/ampere/bbergkpi/softwares/ARGs_OAP/Ublastx_stageone/argoap_pipeline_stagetwo_version2 line 373.
Use of uninitialized value in concatenation (.) or string at /home/ampere/bbergkpi/softwares/ARGs_OAP/Ublastx_stageone/argoap_pipeline_stagetwo_version2 line 373.
This error was displayed a lot so I suppose it's in a for loop or something and it's applied to all files like the next one.

/home/ampere/bbergkpi/softwares/ARGs_OAP/Ublastx_stageone/argoap_pipeline_stagetwo_version2 line 323.


Best,

**Comment by biofuture** [comment]
Hi

It seems that this program was not finished correctly. 
The error message is this "Not KO Maping, wrong datasets", which means in your datasets, no essential single-copy genes was detected.  
1. Firstly, can you check your diamond results for searching the essential single copy genes?
2. Do you have the right datasets to run, what type of data you are using?
