### ISSUE TITLE
Error after remove the usearch in the bin

### ISSUE THREAD

**Issue by lancetxiao** [biofuture/Ublastx_stageone#33]
Hi, When I use your example data to test the new version, 
command line “/data1/yxSoftware/Ublastx_stageone/argoap_pipeline_stageone_version2 -i inputfqs/ -m meta-data.txt -o outT1”
Wrong information shows below;

outT1/ublastx_bash_Fri-May-24-06:07:51-2019.sh: line 4: /data1/yxSoftware/Ublastx_stageone/bin/usearch: No such file or directory
outT1/ublastx_bash_Fri-May-24-06:07:51-2019.sh: line 5: /data1/yxSoftware/Ublastx_stageone/bin/usearch: No such file or directory
outT1/ublastx_bash_Fri-May-24-06:07:51-2019.sh: line 7: /data1/yxSoftware/Ublastx_stageone/bin/usearch: No such file or directory
outT1/ublastx_bash_Fri-May-24-06:07:51-2019.sh: line 8: /data1/yxSoftware/Ublastx_stageone/bin/usearch: No such file or directory

No such file or directory  at /data1/yxSoftware/Ublastx_stageone/bin/extract_usearch_reads.pl line 8.
/data1/yxSoftware/Ublastx_stageone/bin/diamond: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /data1/yxSoftware/Ublastx_stageone/bin/diamond)
/data1/yxSoftware/Ublastx_stageone/bin/diamond: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.15' not found (required by /data1/yxSoftware/Ublastx_stageone/bin/diamond)
/data1/yxSoftware/Ublastx_stageone/bin/diamond: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /data1/yxSoftware/Ublastx_stageone/bin/diamond)
/data1/yxSoftware/Ublastx_stageone/bin/diamond: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.15' not found (required by /data1/yxSoftware/Ublastx_stageone/bin/diamond)
cat: outT1/STAS.uscmg_1.dmd: No such file or directory
cat: outT1/STAS.uscmg_2.dmd: No such file or directory

Could you help me?
Thanks a lot!

**Comment by biofuture** [comment]
We removed the usearch, you need to download the usearch by yourself.

**Comment by lancetxiao** [comment]
And How to rebuild the gg85.udb from and SARGV2.0.udb ?Thanks. I also know nothing about the bioinformations. Thanks again!

**Comment by biofuture** [comment]
downlaod the gg85.fasta from this link.  build udb with usearch with the following command

usearch -makeudb_usearch db.fasta -output db.udb 

Please keep the name the same.
