### ISSUE TITLE
How to rebuild the gg85.udb from and SARGV2.0.udb ?

### ISSUE THREAD

**Issue by lancetxiao** [biofuture/Ublastx_stageone#34]
Hi, again. How to rebuild the gg85.udb from and SARGV2.0.udb ?. I Just download the usearch. Then the test works! Does This affect the results?
<img width="591" alt="image" src="https://user-images.githubusercontent.com/21260389/58295257-ce6f2100-7e00-11e9-92f1-39fb3ed0f58e.png">

<img width="1436" alt="image" src="https://user-images.githubusercontent.com/21260389/58295624-db8d0f80-7e02-11e9-8d57-40d923a993d9.png">
The results shows different with your test resluts!😝
 I almost know nothing about the bioinformations. Thanks again!

**Comment by biofuture** [comment]
download 
https://gg-sg-web.s3-us-west-2.amazonaws.com/downloads/greengenes_database/gg_13_5/gg_13_5_otus.tar.gz

usearch -makeudb_usearch db.fasta -output db.udb
