### ISSUE TITLE
Stage two down?

### ISSUE THREAD

**Issue by koopkaup** [biofuture/Ublastx_stageone#4]
What has happened with the stage two web page http://smile.hku.hk/SARGs? It gives me bad gateway error 502.

**Comment by biofuture** [comment]
Dear Koopkaup

The server encountered some problem and have to reboot, sorry for the inconvenience taken to you.  Just rerun the without the need to reupload your dataset.

**Comment by koopkaup** [comment]
I still get the same error. Is the server online?

**Comment by biofuture** [comment]
I have tested it now.  It should be OK.  Please try it again.

**Comment by koopkaup** [comment]
Now it works, but when I upload the extracted.fa data file then it failes and gives a Gateway timeout error. My fasta file is 1,4 GB. Is there a file size limit?

**Comment by biofuture** [comment]
Files should not exceed 2Gbs, but it is my suggestion that the file should be not over 1 GBs as the uploading may be blocked by unstable internet connection or limited uploading speed.  You can divide the extrated.fa  and metadata_online.txt into two parts or if you can not do it by yourself. You can rerun the stage_one  pipeline for half of the samples and get two extrated.fa.
