### ISSUE TITLE
Normalizedcopynumber	0 in *_R.16s_hvr_normal.copy.txt

### ISSUE THREAD

**Issue by darshanbaral** [biofuture/Ublastx_stageone#5]
Any guesses on why I have `Normalizedcopynumber	0` in all the *_R.16s_hvr_normal.copy.txt

**Comment by biofuture** [comment]
Please check your fasta file to see whether it is correct.  

If the value is 0, this means there is no 16S V6 hit in your sample to the V6 database. For a real sample, it is impossible.

**Comment by darshanbaral** [comment]
I used `fastq` files for the analysis. But I don't think that is the issue. I ran stage one analysis for 49 samples in 3 different runs. The first two runs were timed out. I removed the samples from meta-data (to avoid re-analyzing) if it had 11 output files at the end of a run. If a sample did not have 11 outputs when a run was timed out, I re-analyzed that sample again in the following run.

For each sample there are 11 outputs in the output directory. Out of them only `*.16s_hvr_normal.copy.txt` and `*.16s_hvr_community.txt` are empty. Do you think it is because the runs did not complete. I should note that the last run, which ran successfully also did not give a good output.

I also did not use any `fasta` from ARDB to create database.

**Comment by biofuture** [comment]
Dear darshanbaral

You do not need to download the RefHVR.V6.fa from https://vamps.mbl.edu/data_downloads/refhvr_v6.fa.gz as the RefHVR.V6.fa and RefHVR.V6.taxonomy.txt are paired in the pipeline.  You should have these two files in your DB directory after clone the source code to local. 

As CARD include all the ARDB sequences now, you may not include ARDB into this run. But I still suggest you cat the two together to run the ublastx_stage_one script.

**Comment by darshanbaral** [comment]
That was the problem. Thank you!
