### ISSUE TITLE
Error ： ”Permission denied“ in Ublastx_stageone-2.3

### ISSUE THREAD

**Issue by chunxiao-dcx** [biofuture/Ublastx_stageone#59]
When I inputed: **./argoap_pipeline_stageone_version2.3 -i inputfqs -o testoutdir -m meta-data.txt**

**Error occurs ： ”Permission denied“ in Ublastx_stageone-2.3：**
testoutdir/ublastx_bash_Thu-Jul-1-03:39:54-2021.sh: 21: testoutdir/ublastx_bash_Thu-Jul-1-03:39:54-2021.sh: /home/dcx02/soft--arg/Ublastx_stageone-2.3/bin/minimap2: Permission denied

"chmod 777 -R Ublastx_stageone-2.3"has been executed
How to solve this problem? Thank you for your answer.

**All results of the operation**
diamond v0.9.24.125 | by Benjamin Buchfink <buchfink@gmail.com>
Licensed under the GNU GPL <https://www.gnu.org/licenses/gpl.txt>
Check http://github.com/bbuchfink/diamond for updates.

#CPU threads: 1
Scoring parameters: (Matrix=BLOSUM62 Lambda=0.267 K=0.041 Penalties=11/1)
Temporary directory: testoutdir
Opening the database...  [4.3e-05s]
#Target sequences to report alignments for: 1
Opening the input file...  [1.6e-05s]
Opening the output file...  [1.6e-05s]
Loading query sequences...  [0.19187s]
Masking queries...  [4.96992s]
Building query seed set...  [0.040961s]
Algorithm: Double-indexed
Building query histograms...  [0.167374s]
Allocating buffers...  [4.2e-05s]
Loading reference sequences...  [0.013201s]
Building reference histograms...  [0.090289s]
Allocating buffers...  [1.9e-05s]
Initializing temporary storage...  [0.000368s]
Processing query chunk 0, reference chunk 0, shape 0, index chunk 0.
Building reference index...  [0.114647s]
Building query index...  [0.238256s]
Building seed filter...  [0.023902s]
Searching alignments...  [0.020951s]
Processing query chunk 0, reference chunk 0, shape 0, index chunk 1.
Building reference index...  [0.130791s]
Building query index...  [0.268398s]
Building seed filter...  [0.024763s]
Searching alignments...  [0.023809s]
Processing query chunk 0, reference chunk 0, shape 0, index chunk 2.
Building reference index...  [0.13611s]
Building query index...  [0.271147s]
Building seed filter...  [0.025208s]
Searching alignments...  [0.022269s]
Processing query chunk 0, reference chunk 0, shape 0, index chunk 3.
Building reference index...  [0.109921s]
Building query index...  [0.228434s]
Building seed filter...  [0.022805s]
Searching alignments...  [0.018343s]
Processing query chunk 0, reference chunk 0, shape 1, index chunk 0.
Building reference index...  [0.110173s]
Building query index...  [0.202931s]
Building seed filter...  [0.021365s]
Searching alignments...  [0.016556s]
Processing query chunk 0, reference chunk 0, shape 1, index chunk 1.
Building reference index...  [0.131138s]
Building query index...  [0.230865s]
Building seed filter...  [0.02249s]
Searching alignments...  [0.017908s]
Processing query chunk 0, reference chunk 0, shape 1, index chunk 2.
Building reference index...  [0.134819s]
Building query index...  [0.240733s]
Building seed filter...  [0.02122s]
Searching alignments...  [0.016696s]
Processing query chunk 0, reference chunk 0, shape 1, index chunk 3.
Building reference index...  [0.111666s]
Building query index...  [0.2045s]
Building seed filter...  [0.023264s]
Searching alignments...  [0.014387s]
Deallocating buffers...  [3e-06s]
Computing alignments...  [0.117904s]
Deallocating reference...  [4e-06s]
Loading reference sequences...  [3e-05s]
Deallocating buffers...  [0.000673s]
Deallocating queries...  [0.00109s]
Loading query sequences...  [1.1e-05s]
Closing the input file...  [9e-06s]
Closing the output file...  [3.3e-05s]
Closing the database file...  [4e-06s]
Deallocating taxonomy...  [3e-06s]
Total time = 8.79697s
Reported 187 pairwise alignments, 187 HSPs.
187 queries aligned.
diamond v0.9.24.125 | by Benjamin Buchfink <buchfink@gmail.com>
Licensed under the GNU GPL <https://www.gnu.org/licenses/gpl.txt>
Check http://github.com/bbuchfink/diamond for updates.

#CPU threads: 1
Scoring parameters: (Matrix=BLOSUM62 Lambda=0.267 K=0.041 Penalties=11/1)
Temporary directory: testoutdir
Opening the database...  [6.2e-05s]
#Target sequences to report alignments for: 1
Opening the input file...  [1.9e-05s]
Opening the output file...  [1.9e-05s]
Loading query sequences...  [0.198104s]
Masking queries...  [4.93203s]
Building query seed set...  [0.039817s]
Algorithm: Double-indexed
Building query histograms...  [0.174855s]
Allocating buffers...  [3.5e-05s]
Loading reference sequences...  [0.016956s]
Building reference histograms...  [0.088387s]
Allocating buffers...  [2e-05s]
Initializing temporary storage...  [0.000299s]
Processing query chunk 0, reference chunk 0, shape 0, index chunk 0.
Building reference index...  [0.114901s]
Building query index...  [0.244413s]
Building seed filter...  [0.023111s]
Searching alignments...  [0.017377s]
Processing query chunk 0, reference chunk 0, shape 0, index chunk 1.
Building reference index...  [0.132529s]
Building query index...  [0.26329s]
Building seed filter...  [0.025169s]
Searching alignments...  [0.020443s]
Processing query chunk 0, reference chunk 0, shape 0, index chunk 2.
Building reference index...  [0.136527s]
Building query index...  [0.272537s]
Building seed filter...  [0.02324s]
Searching alignments...  [0.021597s]
Processing query chunk 0, reference chunk 0, shape 0, index chunk 3.
Building reference index...  [0.110438s]
Building query index...  [0.222314s]
Building seed filter...  [0.023954s]
Searching alignments...  [0.017669s]
Processing query chunk 0, reference chunk 0, shape 1, index chunk 0.
Building reference index...  [0.1091s]
Building query index...  [0.211217s]
Building seed filter...  [0.022024s]
Searching alignments...  [0.015815s]
Processing query chunk 0, reference chunk 0, shape 1, index chunk 1.
Building reference index...  [0.130472s]
Building query index...  [0.230229s]
Building seed filter...  [0.020563s]
Searching alignments...  [0.01597s]
Processing query chunk 0, reference chunk 0, shape 1, index chunk 2.
Building reference index...  [0.135327s]
Building query index...  [0.232558s]
Building seed filter...  [0.021087s]
Searching alignments...  [0.01535s]
Processing query chunk 0, reference chunk 0, shape 1, index chunk 3.
Building reference index...  [0.109775s]
Building query index...  [0.195935s]
Building seed filter...  [0.021279s]
Searching alignments...  [0.016868s]
Deallocating buffers...  [5e-06s]
Computing alignments...  [0.091815s]
Deallocating reference...  [5e-06s]
Loading reference sequences...  [1.4e-05s]
Deallocating buffers...  [0.000712s]
Deallocating queries...  [0.000869s]
Loading query sequences...  [1e-05s]
Closing the input file...  [7e-06s]
Closing the output file...  [3.7e-05s]
Closing the database file...  [4e-06s]
Deallocating taxonomy...  [2e-06s]
Total time = 8.72003s
Reported 163 pairwise alignments, 163 HSPs.
163 queries aligned.
java -ea -Xmx932m -cp /home/dcx02/soft--arg/Ublastx_stageone-2.3/bin/bbmap/current/ jgi.SplitPairsAndSingles rp in1=inputfqs/STAS_1.fa in2=inputfqs/STAS_2.fa out1=testoutdir/STAS_fixed_1.fa out2=testoutdir/STAS_fixed_2.fa outs=testoutdir/STAS_singletons.fa repair
Executing jgi.SplitPairsAndSingles [rp, in1=inputfqs/STAS_1.fa, in2=inputfqs/STAS_2.fa, out1=testoutdir/STAS_fixed_1.fa, out2=testoutdir/STAS_fixed_2.fa, outs=testoutdir/STAS_singletons.fa, repair]

Set INTERLEAVED to false
Started output stream.

Input:                  	200000 reads 		20000000 bases.
Result:                 	200000 reads (100.00%) 	20000000 bases (100.00%)
Pairs:                  	200000 reads (100.00%) 	20000000 bases (100.00%)
Singletons:             	0 reads (0.00%) 	0 bases (0.00%)

Time:                         	1.963 seconds.
Reads Processed:        200k 	101.87k reads/sec
Bases Processed:      20000k 	10.19m bases/sec
testoutdir/ublastx_bash_Thu-Jul-1-03:39:54-2021.sh: 7: testoutdir/ublastx_bash_Thu-Jul-1-03:39:54-2021.sh: /home/dcx02/soft--arg/Ublastx_stageone-2.3/bin/minimap2: Permission denied
diamond v0.9.24.125 | by Benjamin Buchfink <buchfink@gmail.com>
Licensed under the GNU GPL <https://www.gnu.org/licenses/gpl.txt>
Check http://github.com/bbuchfink/diamond for updates.

#CPU threads: 1
Scoring parameters: (Matrix=BLOSUM62 Lambda=0.267 K=0.041 Penalties=11/1)
Temporary directory: testoutdir
Opening the database...  [5e-05s]
#Target sequences to report alignments for: 1
Opening the input file...  [3.1e-05s]
Opening the output file...  [3.3e-05s]
Loading query sequences...  [0.20886s]
Masking queries...  [4.96087s]
Building query seed set...  [0.041325s]
Algorithm: Double-indexed
Building query histograms...  [0.176603s]
Allocating buffers...  [4e-05s]
Loading reference sequences...  [0.014069s]
Building reference histograms...  [0.091368s]
Allocating buffers...  [2.1e-05s]
Initializing temporary storage...  [0.000401s]
Processing query chunk 0, reference chunk 0, shape 0, index chunk 0.
Building reference index...  [0.127991s]
Building query index...  [0.523039s]
Building seed filter...  [0.022468s]
Searching alignments...  [0.025008s]
Processing query chunk 0, reference chunk 0, shape 0, index chunk 1.
Building reference index...  [0.132279s]
Building query index...  [0.262306s]
Building seed filter...  [0.023803s]
Searching alignments...  [0.02518s]
Processing query chunk 0, reference chunk 0, shape 0, index chunk 2.
Building reference index...  [0.141857s]
Building query index...  [0.27486s]
Building seed filter...  [0.024479s]
Searching alignments...  [0.025164s]
Processing query chunk 0, reference chunk 0, shape 0, index chunk 3.
Building reference index...  [0.226111s]
Building query index...  [0.241786s]
Building seed filter...  [0.023981s]
Searching alignments...  [0.023277s]
Processing query chunk 0, reference chunk 0, shape 1, index chunk 0.
Building reference index...  [0.117959s]
Building query index...  [0.221351s]
Building seed filter...  [0.022539s]
Searching alignments...  [0.020105s]
Processing query chunk 0, reference chunk 0, shape 1, index chunk 1.
Building reference index...  [0.143249s]
Building query index...  [0.258097s]
Building seed filter...  [0.023948s]
Searching alignments...  [0.018716s]
Processing query chunk 0, reference chunk 0, shape 1, index chunk 2.
Building reference index...  [0.149724s]
Building query index...  [0.257747s]
Building seed filter...  [0.023157s]
Searching alignments...  [0.091998s]
Processing query chunk 0, reference chunk 0, shape 1, index chunk 3.
Building reference index...  [0.115044s]
Building query index...  [0.21822s]
Building seed filter...  [0.024215s]
Searching alignments...  [0.020359s]
Deallocating buffers...  [4e-06s]
Computing alignments...  [0.261309s]
Deallocating reference...  [1.7e-05s]
Loading reference sequences...  [1.8e-05s]
Deallocating buffers...  [0.000593s]
Deallocating queries...  [0.000954s]
Loading query sequences...  [1.1e-05s]
Closing the input file...  [8e-06s]
Closing the output file...  [2.7e-05s]
Closing the database file...  [1.3e-05s]
Deallocating taxonomy...  [7e-06s]
Total time = 9.60917s
Reported 206 pairwise alignments, 206 HSPs.
206 queries aligned.
diamond v0.9.24.125 | by Benjamin Buchfink <buchfink@gmail.com>
Licensed under the GNU GPL <https://www.gnu.org/licenses/gpl.txt>
Check http://github.com/bbuchfink/diamond for updates.

#CPU threads: 1
Scoring parameters: (Matrix=BLOSUM62 Lambda=0.267 K=0.041 Penalties=11/1)
Temporary directory: testoutdir
Opening the database...  [4.8e-05s]
#Target sequences to report alignments for: 1
Opening the input file...  [2.4e-05s]
Opening the output file...  [6.5e-05s]
Loading query sequences...  [0.191116s]
Masking queries...  [5.03313s]
Building query seed set...  [0.041266s]
Algorithm: Double-indexed
Building query histograms...  [0.183597s]
Allocating buffers...  [0.006557s]
Loading reference sequences...  [0.016129s]
Building reference histograms...  [0.09997s]
Allocating buffers...  [2.2e-05s]
Initializing temporary storage...  [0.000329s]
Processing query chunk 0, reference chunk 0, shape 0, index chunk 0.
Building reference index...  [0.127899s]
Building query index...  [0.469226s]
Building seed filter...  [0.023444s]
Searching alignments...  [0.022956s]
Processing query chunk 0, reference chunk 0, shape 0, index chunk 1.
Building reference index...  [0.128997s]
Building query index...  [0.26645s]
Building seed filter...  [0.024398s]
Searching alignments...  [0.021826s]
Processing query chunk 0, reference chunk 0, shape 0, index chunk 2.
Building reference index...  [0.143788s]
Building query index...  [0.289031s]
Building seed filter...  [0.023489s]
Searching alignments...  [0.022618s]
Processing query chunk 0, reference chunk 0, shape 0, index chunk 3.
Building reference index...  [0.118793s]
Building query index...  [0.243551s]
Building seed filter...  [0.024894s]
Searching alignments...  [0.022192s]
Processing query chunk 0, reference chunk 0, shape 1, index chunk 0.
Building reference index...  [0.119673s]
Building query index...  [0.217528s]
Building seed filter...  [0.023369s]
Searching alignments...  [0.019387s]
Processing query chunk 0, reference chunk 0, shape 1, index chunk 1.
Building reference index...  [0.143328s]
Building query index...  [0.254035s]
Building seed filter...  [0.021694s]
Searching alignments...  [0.018239s]
Processing query chunk 0, reference chunk 0, shape 1, index chunk 2.
Building reference index...  [0.149356s]
Building query index...  [0.260074s]
Building seed filter...  [0.022028s]
Searching alignments...  [0.01799s]
Processing query chunk 0, reference chunk 0, shape 1, index chunk 3.
Building reference index...  [0.118833s]
Building query index...  [0.21992s]
Building seed filter...  [0.022004s]
Searching alignments...  [0.01816s]
Deallocating buffers...  [5e-06s]
Computing alignments...  [0.120297s]
Deallocating reference...  [5e-06s]
Loading reference sequences...  [1.4e-05s]
Deallocating buffers...  [0.000907s]
Deallocating queries...  [0.001437s]
Loading query sequences...  [1.3e-05s]
Closing the input file...  [8e-06s]
Closing the output file...  [3e-05s]
Closing the database file...  [6e-06s]
Deallocating taxonomy...  [2e-06s]
Total time = 9.31677s
Reported 211 pairwise alignments, 211 HSPs.
211 queries aligned.
java -ea -Xmx931m -cp /home/dcx02/soft--arg/Ublastx_stageone-2.3/bin/bbmap/current/ jgi.SplitPairsAndSingles rp in1=inputfqs/SWHAS104_1.fa in2=inputfqs/SWHAS104_2.fa out1=testoutdir/SWHAS104_fixed_1.fa out2=testoutdir/SWHAS104_fixed_2.fa outs=testoutdir/SWHAS104_singletons.fa repair
Executing jgi.SplitPairsAndSingles [rp, in1=inputfqs/SWHAS104_1.fa, in2=inputfqs/SWHAS104_2.fa, out1=testoutdir/SWHAS104_fixed_1.fa, out2=testoutdir/SWHAS104_fixed_2.fa, outs=testoutdir/SWHAS104_singletons.fa, repair]

Set INTERLEAVED to false
Started output stream.

Input:                  	200000 reads 		20000000 bases.
Result:                 	200000 reads (100.00%) 	20000000 bases (100.00%)
Pairs:                  	200000 reads (100.00%) 	20000000 bases (100.00%)
Singletons:             	0 reads (0.00%) 	0 bases (0.00%)

Time:                         	1.746 seconds.
Reads Processed:        200k 	114.53k reads/sec
Bases Processed:      20000k 	11.45m bases/sec
testoutdir/ublastx_bash_Thu-Jul-1-03:39:54-2021.sh: 21: testoutdir/ublastx_bash_Thu-Jul-1-03:39:54-2021.sh: /home/dcx02/soft--arg/Ublastx_stageone-2.3/bin/minimap2: Permission denied

**Comment by biofuture** [comment]
you need to change the execution of  minimap2;  chmod  -R 755 Ublastx_stageone-2.3/bin/

**Comment by chunxiao-dcx** [comment]
I have input"chmod 777 -R Ublastx_stageone-2.3", but it showed the same error: Permission denied





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "biofuture/Ublastx_stageone"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月1日(星期四) 中午12:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [biofuture/Ublastx_stageone] Error ： ”Permission denied“ in Ublastx_stageone-2.3 (#59)





 
you need to change the execution of  minimap2;  chmod  -R 755 Ublastx_stageone-2.3/bin/

**Comment by biofuture** [comment]
You need to make the minimap2 executable in your linux system 

chmod 755 Ublastx_stageone-2.3/bin/minimap2
