### ISSUE TITLE
Normalization Equation

### ISSUE THREAD

**Issue by darshanbaral** [biofuture/Ublastx_stageone#6]
I am writing about the normalization equation for 16S described in the paper "_ARGs-OAP: online analysis pipeline for antibiotic resistance genes detection from metagenomic data using an integrated structured ARG-database_" (https://academic.oup.com/bioinformatics/article/32/15/2346/1743463).

What is the difference between the **L<sub>reads</sub>** in the numerator and the denominator. If they are the same, don't they cancel out?

**Comment by biofuture** [comment]
Yes, you are right. For one sample, they are the same. We leave them there to make the whole process much more clear for the reader to understand.

**Comment by slvrshot** [comment]
> I am writing about the normalization equation for 16S described in the paper "_ARGs-OAP: online analysis pipeline for antibiotic resistance genes detection from metagenomic data using an integrated structured ARG-database_" (https://academic.oup.com/bioinformatics/article/32/15/2346/1743463).
> 
> What is the difference between the **Lreads** in the numerator and the denominator. If they are the same, don't they cancel out?

Were you able to figure out the equation? I am struggling to determine what "n" is from ARGS-OAP. And is the N-ARGs like sequences the total number of ARGs in the database? N-16S sequence should be the copy number in the metadata online file correct?
