### ISSUE TITLE
Typical memory usage for a metagenome?

### ISSUE THREAD

**Issue by AdeBC** [biofuture/Ublastx_stageone#70]
Do you have a suggested hardware configuration for running the analysis for a metagenome? especially the minimum memory required. 

Thanks!

**Comment by biofuture** [comment]
Hi,
Generally, you can run this on any computer without too much memory.  20 Gb
should be enough.
Regards,

Xiao-Tao Jiang, Ph.D.
Postdoc Research Fellow
Microbiome Research Centre
St George and Sutherland Clinical School
UNSW Sydney


Hui-Chong ***@***.***> 于2022年2月25日周五 21:36写道：

**Comment by AdeBC** [comment]
Thank you for your great work and reply.
